language: python
dist: jammy  # Ubuntu 22.04
python: "3.10"

install:
    - pip install -q -r requirements-dev.txt
scripts:
    - pylint games_review

branches:
  only:
    - main  # Executa apenas em pushs na branch main

# Garante que testes rodem também em pull requests
jobs:
  include:
    - if: type = pull_request